version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libtirpc-dev
    - r-base
    - r-base-dev
  commands:
    - sudo apt update
    - sudo apt install -y r-base r-base-dev libtirpc-dev
    - Rscript -e "install.packages('nnTensor', repos='https://cloud.r-project.org')"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py