version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libtirpc-dev
    - r-base
    - r-base-dev
  commands:
    # Use a multi-line scalar and explicitly call Rscript
    - |
      /usr/bin/Rscript -e "install.packages('nnTensor', repos='https://cloud.r-project.org')"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py