version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libtirpc-dev
    - r-base
    - r-base-dev
  jobs:
    pre_build:
      - |
        R_LIBS_ABS="$READTHEDOCS_PROJECT_DIR/R-packages"
        mkdir -p $R_LIBS_ABS
        /usr/bin/Rscript -e "install.packages(\"nnTensor\", repos=\"https://cloud.r-project.org\", lib=\"$R_LIBS_ABS\")"
        export R_LIBS="$R_LIBS_ABS"
        /usr/bin/Rscript -e ".libPaths()"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py