version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libtirpc-dev
    - r-base
    - r-base-dev
  jobs:
    post_checkout:
      - |
        if [ -d "$READTHEDOCS_VIRTUALENV_PATH/../r-packages-cache" ]; then
          cp -r "$READTHEDOCS_VIRTUALENV_PATH/../r-packages-cache" R-packages
          echo "Restored R packages from cache"
        fi
    pre_build:
      - |
        pip install uv
        uv pip install .[docs]
        mkdir -p R-packages
        export R_LIBS="R-packages"
        if ! /usr/bin/Rscript -e "library(nnTensor)" 2>/dev/null; then
          echo "Installing nnTensor..."
          /usr/bin/Rscript -e "install.packages(\"nnTensor\", repos=\"https://cloud.r-project.org\", lib=Sys.getenv(\"R_LIBS\"), Ncpus=2, INSTALL_opts=\"--no-docs --no-html --no-help\")"
        else
          echo "nnTensor already installed from cache"
        fi
    post_build:
      - |
        if [ -d "R-packages" ]; then
          mkdir -p "$READTHEDOCS_VIRTUALENV_PATH/../r-packages-cache"
          cp -r R-packages/* "$READTHEDOCS_VIRTUALENV_PATH/../r-packages-cache/"
          echo "Cached R packages for next build"
        fi
sphinx:
  configuration: docs/conf.py