version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - r-base
  jobs:
    pre_build:
      - |
        mkdir -p R-packages
        export R_LIBS="R-packages"
        /usr/bin/Rscript -e "install.packages(\"nnTensor\", repos=\"https://packagemanager.rstudio.com/all/__linux__/focal/latest\", lib=Sys.getenv(\"R_LIBS\"))"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py