version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libtirpc-dev
    - r-base
    - r-base-dev
  jobs:
    pre_build:
      - |
        # 1. Create a writable directory for R packages
        mkdir -p R-packages
        
        # 2. Install the package into the writable 'R-packages' directory.
        #    We escape the quotes for the R strings (") and specify the 'lib' path.
        /usr/bin/Rscript -e "install.packages(\"nnTensor\", repos=\"https://cloud.r-project.org\", lib=\"R-packages\")"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  configuration: docs/conf.py