version: 2

build:
  os: ubuntu-lts-latest
  jobs:
    pre_build:
      - echo "External CI build is enabled. Skipping internal build steps."
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs