import os

import numpy as np

RANDOM_STATE = 42

RESULTS_FOLDER = 'results'
AUX_DATA_FOLDER = "aux_data"
PROFILES_FOLDER = 'profiles'
PROFILES_PATH = os.path.join(AUX_DATA_FOLDER, PROFILES_FOLDER)
PAPER_RESULTS_FOLDER = "paper_results"

COMPLETE_SUBRESULTS_FOLDER = 'complete_subresults'
INCOMPLETE_SUBRESULTS_FOLDER = 'incomplete_subresults'
FILLED_SUBRESULTS_FOLDER = 'filled_subresults'
COMPLETE_SUBRESULTS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_SUBRESULTS_FOLDER)
INCOMPLETE_SUBRESULTS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_SUBRESULTS_FOLDER)
FILLED_SUBRESULTS_PATH = os.path.join(RESULTS_FOLDER, FILLED_SUBRESULTS_FOLDER)


COMPLETE_RESULTS_FILE = 'complete_algorithms_evaluation.csv'
INCOMPLETE_RESULTS_FILE = 'incomplete_algorithms_evaluation.csv'
FILLED_RESULTS_FILE = 'filled_algorithms_evaluation.csv'
TIME_RESULTS_FILE = 'time_evaluation.csv'
DATASET_TABLE = "dataset_table.csv"
COMPARISON_ALG_FILE = "alg_comparisons.csv"
COMPLETE_RESULTS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_RESULTS_FILE)
INCOMPLETE_RESULTS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_RESULTS_FILE)
FILLED_RESULTS_PATH = os.path.join(RESULTS_FOLDER, FILLED_RESULTS_FILE)
TIME_RESULTS_PATH = os.path.join(RESULTS_FOLDER, TIME_RESULTS_FILE)
DATASET_TABLE_PATH = os.path.join(AUX_DATA_FOLDER, DATASET_TABLE)
COMPARISON_ALG_PATH = os.path.join(RESULTS_FOLDER, COMPARISON_ALG_FILE)

COMPLETE_LOGS_FILE = 'complete_logs.txt'
INCOMPLETE_LOGS_FILE = 'incomplete_logs.txt'
FILLED_LOGS_FILE = 'filled_logs.txt'
TIME_LOGS_FILE = 'time_logs.txt'
COMPLETE_LOGS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_LOGS_FILE)
INCOMPLETE_LOGS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_LOGS_FILE)
FILLED_LOGS_PATH = os.path.join(RESULTS_FOLDER, FILLED_LOGS_FILE)
TIME_LOGS_PATH = os.path.join(RESULTS_FOLDER, TIME_LOGS_FILE)

COMPLETE_ERRORS_FILE = 'complete_errors.txt'
INCOMPLETE_ERRORS_FILE = 'incomplete_errors.txt'
FILLED_ERRORS_FILE = 'filled_errors.txt'
TIME_ERRORS_FILE = 'time_errors.txt'
COMPLETE_ERRORS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_ERRORS_FILE)
INCOMPLETE_ERRORS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_ERRORS_FILE)
FILLED_ERRORS_PATH = os.path.join(RESULTS_FOLDER, FILLED_ERRORS_FILE)
TIME_ERRORS_PATH = os.path.join(RESULTS_FOLDER, TIME_ERRORS_FILE)

COMPLETE_METRICS_FILE = 'complete_algorithms_metrics.csv'
INCOMPLETE_METRICS_FILE = 'incomplete_algorithms_metrics.csv'
COMPLETE_METRICS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_METRICS_FILE)
INCOMPLETE_METRICS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_METRICS_FILE)

COMPLETE_RBMETRICS_FILE = 'complete_algorithms_inmetrics.csv'
INCOMPLETE_RBMETRICS_FILE = 'incomplete_algorithms_inmetrics.csv'
COMPLETE_RBMETRICS_PATH = os.path.join(RESULTS_FOLDER, COMPLETE_RBMETRICS_FILE)
INCOMPLETE_RBMETRICS_PATH = os.path.join(RESULTS_FOLDER, INCOMPLETE_RBMETRICS_FILE)

UNS_METRICS_COMPLETE_ALG_FILE = "uns_metrics_by_com_alg.csv"
UNS_METRICS_COMPLETE_ALG_PATH = os.path.join(RESULTS_FOLDER, UNS_METRICS_COMPLETE_ALG_FILE)
UNS_METRICS_INCOMPLETE_ALG_FILE = "uns_metrics_by_inc_alg.csv"
UNS_METRICS_INCOMPLETE_ALG_PATH = os.path.join(RESULTS_FOLDER, UNS_METRICS_INCOMPLETE_ALG_FILE)


amputation_mechanisms = ["um", 'mcar', 'mnar', "pm"]
probs = np.arange(100, step= 10)
imputation = [True, False]
runs_per_alg = np.arange(30)
runs_per_long_alg = 1
TIME_LIMIT = 300
EXTREME_TIME_LIMIT = 3600

