import os
import numpy as np
import oct2py
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.cluster import KMeans

from ..utils import check_Xs, DatasetUtils


class LFIMVC(BaseEstimator, ClassifierMixin):
    r"""
    Late Fusion Incomplete Multi-View Clustering (LF-IMVC).

    LF-IMVC jointly learns a consensus clustering matrix, imputes each incomplete base matrix, and optimizes the
    corresponding permutation matrices to integrate the incomplete clustering matrices generated by incomplete views.

    Parameters
    ----------
    n_clusters : int, default=8
        The number of clusters to generate. If it is a list, the number of clusters will be estimated by the algorithm
         with this range of number of clusters to choose between.
    normalize : bool, default True
        If True, it will normalize and center the kernel.
    kernel : str or callable, default="default"
        Specifies the kernel type to be used in the algorithm. Currently only "default" and "precomputed" are accepted.
    lambda_reg : float, default=1.
        Regularization parameter. The algorithm demonstrated stable performance across a wide range of
        this hyperparameter.
    random_state : int, default=None
        Determines the randomness. Use an int to make the randomness deterministic.
    engine : str, default=matlab
        Engine to use for computing the model.
.   verbose : bool, default=False
        Verbosity mode.

    Attributes
    ----------
    labels_ : array-like of shape (n_samples,)
        Labels of each point in training data.
    H_ : array-like
        Consensus clustering matrix.
    WP_ : array-like
        p-th permutation matrix.
    HP_ : array-like
        missing part of the p-th base clustering matrix.
    loss_ : float
        Value of the loss function.

    References
    ----------
    [paper] X. Liu et al., "Late Fusion Incomplete Multi-View Clustering," in IEEE Transactions on Pattern Analysis
             and Machine Intelligence, vol. 41, no. 10, pp. 2410-2423, 1 Oct. 2019, doi: 10.1109/TPAMI.2018.2879108.
    [code]   https://github.com/xinwangliu/Late-Fusion-Incomplete-Multi-view-Clustering

    Examples
    --------
    >>> from imvc.datasets import LoadDataset
    >>> from imvc.cluster import LFIMVC
    >>> Xs = LoadDataset.load_dataset(dataset_name="nutrimouse")
    >>> estimator = LFIMVC(n_clusters = 2)
    >>> labels = estimator.fit_predict(Xs)
    """

    def __init__(self, n_clusters: int = 8, normalize: bool = True, kernel = "default", lambda_reg: float = 1.,
                 random_state:int = None, engine: str ="matlab", verbose = False):
        self.n_clusters = n_clusters
        self.normalize = normalize
        self.kernel = kernel
        self.kernel_function = kernel if callable(kernel) else eval(f"self._kernel_{kernel}")
        self.lambda_reg = lambda_reg
        self.random_state = random_state
        self.engine = engine
        self.verbose = verbose


    def fit(self, Xs, y=None):
        r"""
        Fit the transformer to the input data.

        Parameters
        ----------
        Xs : list of array-likes
            - Xs length: n_views
            - Xs[i] shape: (n_samples, n_features_i)
            A list of different views.
        y : Ignored
            Not used, present here for API consistency by convention.

        Returns
        -------
        self :  Fitted estimator.
        """
        Xs = check_Xs(Xs, force_all_finite='allow-nan')

        if self.engine=="matlab":
            matlab_folder = os.path.join("imvc", "cluster", "_lfimvc")
            matlab_files = ['IncompleteMultikernelLatefusionclusteringV1Hv.m', 'updateHPabsentClusteringV1.m',
                            'updateWPabsentClusteringV1.m', "kcenter.m", "knorm.m", "mykernelkmeans.m"]
            oc = oct2py.Oct2Py(temp_dir= matlab_folder)
            for matlab_file in matlab_files:
                with open(os.path.join(matlab_folder, matlab_file)) as f:
                    oc.eval(f.read())

            transformed_Xs = self.kernel_function(Xs=Xs)

            if self.random_state is not None:
                oc.rand("seed", self.random_state)
            U, WP,HP, obj = oc.IncompleteMultikernelLatefusionclusteringV1Hv(transformed_Xs, self.n_clusters,
                                                                             self.lambda_reg, int(self.normalize),
                                                                             nout=4)
        else:
            raise ValueError("Only engine=='matlab' is currently supported.")

        model = KMeans(n_clusters= self.n_clusters, random_state= self.random_state)
        self.labels_ = model.fit_predict(X= U)
        self.H_, self.WP_, self.HP_, self.loss_ = U, WP, HP, obj

        return self


    def _predict(self, Xs):
        r"""
        Return clustering results for samples.

        Parameters
        ----------
        Xs : list of array-likes
            - Xs length: n_views
            - Xs[i] shape: (n_samples, n_features_i)
            A list of different views.

        Returns
        -------
        labels : ndarray of shape (n_samples,)
            Index of the cluster each sample belongs to.
        """
        return self.labels_


    def fit_predict(self, Xs, y=None):
        r"""
        Fit the model and return clustering results.
        Convenience method; equivalent to calling fit(X) followed by predict(X).

        Parameters
        ----------
        Xs : list of array-likes
            - Xs length: n_views
            - Xs[i] shape: (n_samples, n_features_i)
            A list of different views.

        Returns
        -------
        labels : ndarray of shape (n_samples,)
            Index of the cluster each sample belongs to.
        """

        labels = self.fit(Xs)._predict(Xs)
        return labels


    @staticmethod
    def _kernel_default(Xs):
        transformed_Xs = [(X @ X.T).fillna(0) for X in Xs]
        transformed_Xs = np.array(transformed_Xs).swapaxes(0,-1)
        return transformed_Xs


    @staticmethod
    def _kernel_precomputed(self, Xs):
        return Xs
